[build]
  publish = './packages/website/out'
  command = 'yarn website:build'

[[redirects]]
  from = "https://figma-export.netlify.app/*"
  to = "https://figma-export.marcomontalbano.com/:splat"
  force = true
